// Copia local de useSalaData (antes en sala-prueba)
import { useState, useEffect, useMemo, useCallback, useRef } from 'react';
import { anchorPoints } from '../config/anchorPoints';
import { FRONT_CENTER, BACK_CENTER, HALF_HALL_D } from '../sceneConfig';
const DEBUG_SALA = false;
const DEBUG_ALLOC = false;
function detectArtworkType(tecnica){ if(!tecnica) return 'painting'; const t=tecnica.toLowerCase(); if(t.includes('fotograf')||t.includes('digital')) return 'photo'; if(t.includes('escultur')||t.includes('relieve')) return 'relief'; if(t.includes('mixta')||t.includes('mix')) return 'mixed'; return 'painting'; }
function getMockSalaData(){ return { id:'mock-sala', nombre:'Sala Mock', descripcion:'Datos simulados', murales:[], _count:{ murales:0 } }; }
const classifyAnchors = (points)=>{ const sections={ rf:[], lf:[], rm:[], lm:[], rb:[], lb:[], bw:[] }; for(const a of points){ if(a.normal && a.normal[2]<0) continue; switch(a.wall){ case 'right-front': sections.rf.push(a); break; case 'left-front': sections.lf.push(a); break; case 'right-mid': sections.rm.push(a); break; case 'left-mid': sections.lm.push(a); break; case 'right-back': sections.rb.push(a); break; case 'left-back': sections.lb.push(a); break; case 'back': sections.bw.push(a); break; default: break; } } const sortDescZ=arr=>arr.sort((a,b)=>b.position[2]-a.position[2]); const sortAscZ=arr=>arr.sort((a,b)=>a.position[2]-b.position[2]); sortDescZ(sections.rf); sortDescZ(sections.lf); sortDescZ(sections.rm); sortDescZ(sections.lm); sortAscZ(sections.rb); sortAscZ(sections.lb); const pathOrdered=[...sections.rf,...sections.lf,...sections.rm,...sections.lm,...sections.rb,...sections.lb,...sections.bw]; return { sections, pathOrdered }; };
let _anchorCache=null; function getAnchorClassification(){ if(!_anchorCache || _anchorCache.source!==anchorPoints){ _anchorCache={ source:anchorPoints, ...classifyAnchors(anchorPoints)}; } return _anchorCache; }
export function useSalaData(salaId=null, options={}){ const { allowMockOnErrorWhenId = true } = options; const [sala,setSala]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(null); const abortRef=useRef(null);
  const fetchFirstAvailableSala=useCallback(async()=>{ abortRef.current?.abort(); const controller=new AbortController(); abortRef.current=controller; setLoading(true); setError(null); try{ const response=await fetch('/api/salas',{ signal:controller.signal }); if(!response.ok) throw new Error(`API error: ${response.status}`); const data=await response.json(); const salas=data.salas||[]; let picked=salas.find(s=> s.nombre==='Colección ARPA' || (s.id===1 && s.murales?.length)); if(!picked) picked=salas.find(s=> s.murales && s.murales.length>0); if(!picked) picked=getMockSalaData(); setSala(picked); }catch(err){ if(err.name==='AbortError') return; setSala(getMockSalaData()); setError(err.message); } finally { setLoading(false); } },[]);
  const fetchSalaById=useCallback(async(id)=>{ abortRef.current?.abort(); const controller=new AbortController(); abortRef.current=controller; setLoading(true); setError(null); try{ const response=await fetch(`/api/salas/${id}`,{ signal:controller.signal }); if(!response.ok) throw new Error(`Sala ${id} no encontrada`); const data=await response.json(); const salaData=data.sala||data; setSala(salaData); }catch(err){ if(err.name==='AbortError') return; if(allowMockOnErrorWhenId){ setSala(getMockSalaData()); } else { setSala(null); } setError(err.message); } finally { setLoading(false); } },[allowMockOnErrorWhenId]);
  useEffect(()=>{ salaId ? fetchSalaById(salaId) : fetchFirstAvailableSala(); return ()=> abortRef.current?.abort(); },[salaId, fetchSalaById, fetchFirstAvailableSala]);
  const artworksRaw = useMemo(()=>{ if(!sala?.murales?.length) return []; const converted = sala.murales.map(sm=>{ const mural=sm.mural||sm; if(!mural) return null; const scale=sm.scale||1; const widthBase=6; const heightBase=4.5; return { id:mural.id, titulo:mural.titulo, title:mural.titulo, autor:mural.autor, artist:mural.autor, anio:mural.anio, year:mural.anio, technique:mural.tecnica, tecnica:mural.tecnica, descripcion:mural.descripcion, imageUrl:mural.imagenUrlWebp||mural.url_imagen, imagenUrlWebp:mural.imagenUrlWebp, url_imagen:mural.url_imagen, width:Math.max(widthBase*scale,widthBase), height:Math.max(heightBase*scale,heightBase), type:detectArtworkType(mural.tecnica), frameStyle:sm.frameStyle||'classic', frameMaterial:'wood', animated:false, anchorId:null, position: sm.pos ? [sm.pos.x, sm.pos.y, sm.pos.z] : null, rotation: sm.rot ? [sm.rot.x, sm.rot.y, sm.rot.z] : null, scale, spotlightIntensity: sm.spotlightIntensity || 1 }; }).filter(Boolean); return converted.slice(0, anchorPoints.length); },[sala]);
  const allocateAnchors = useCallback((arts)=>{ if(!arts.length) return []; const { pathOrdered } = getAnchorClassification(); if(!pathOrdered.length) return arts.map(a=>({...a,anchorId:null}));
  // Advanced no-overlap allocation (adapted)
  const WALL_PRIORITY_ORDER=['right-front','left-front','divider-front','right-mid','left-mid','divider-back','right-back','left-back','back'];
  const sorted=[...arts].sort((a,b)=> b.width*b.height - a.width*a.height);
  const anchorsByWall=new Map(); for(const w of WALL_PRIORITY_ORDER) anchorsByWall.set(w,[]); for(const a of pathOrdered){ if(!anchorsByWall.has(a.wall)) anchorsByWall.set(a.wall,[]); anchorsByWall.get(a.wall).push(a); }
  const wallQueues=WALL_PRIORITY_ORDER.filter(w=>(anchorsByWall.get(w)||[]).length);
  const placed=[]; const used=new Set();
  const crossesDivider=(art,anchor)=>{ if(!anchor) return false; const wall=anchor.wall||''; const lateral=wall.includes('right')||wall.includes('left'); if(!lateral) return false; const halfSpan=(art.width||6)*0.5; const zMin=anchor.position[2]-halfSpan; const zMax=anchor.position[2]+halfSpan; const divA=FRONT_CENTER - HALF_HALL_D; const divB=BACK_CENTER + HALF_HALL_D; const M=0.6; if(zMin-M < divA && zMax+M > divA) return true; if(zMin-M < divB && zMax+M > divB) return true; return false; };
  const willOverlap=(art,anchor,placedList)=>{ if(!anchor) return false; const wall=anchor.wall; const axisIndex=(wall.includes('back')||wall.includes('divider'))?0:2; const span=art.width||6; const half=span*0.5; const pos=anchor.position[axisIndex]; const min=pos-half; const max=pos+half; for(const p of placedList){ if(p.wall!==wall) continue; const oArt=p.art; const oAnchor=p.anchor; const oPos=oAnchor.position[axisIndex]; const oHalf=(oArt.width||6)*0.5; const oMin=oPos-oHalf; const oMax=oPos+oHalf; if(!(max<oMin || min>oMax)) return true; } return false; };
  for(const art of sorted){ let chosen=null; for(let wi=0; wi<wallQueues.length && !chosen; wi++){ const wall=wallQueues[wi]; const list=anchorsByWall.get(wall)||[]; for(let ai=0; ai<list.length; ai++){ const cand=list[ai]; if(used.has(cand.id)) continue; if(crossesDivider(art,cand)) continue; if(willOverlap(art,cand,placed)) continue; chosen=cand; break; } }
    if(!chosen){ for(const cand of pathOrdered){ if(used.has(cand.id)) continue; if(crossesDivider(art,cand)) continue; if(willOverlap(art,cand,placed)) continue; chosen=cand; break; } }
    if(chosen){ used.add(chosen.id); placed.push({ art, anchor:chosen, wall:chosen.wall }); }
  }
  const assignments=new Map(placed.map(p=>[p.art.id,p.anchor.id]));
  return arts.map(a=>({...a, anchorId:assignments.get(a.id)||null })); },[FRONT_CENTER, HALF_HALL_D, BACK_CENTER]);
  const artworks = useMemo(()=> allocateAnchors(artworksRaw), [artworksRaw, allocateAnchors]);
  return { sala, artworks, loading, error, refresh: ()=> { salaId ? fetchSalaById(salaId) : fetchFirstAvailableSala(); } };
}
