-- AlterTable
ALTER TABLE "Sala" ADD COLUMN     "ambientIntensity" DOUBLE PRECISION DEFAULT 0.8,
ADD COLUMN     "audioZones" JSONB,
ADD COLUMN     "fogColor" TEXT,
ADD COLUMN     "fogFar" DOUBLE PRECISION,
ADD COLUMN     "fogNear" DOUBLE PRECISION,
ADD COLUMN     "layoutVersion" INTEGER DEFAULT 1,
ADD COLUMN     "lightingPreset" TEXT,
ADD COLUMN     "navigationMeshId" TEXT;

-- AlterTable
ALTER TABLE "SalaMural" ADD COLUMN     "frameStyle" TEXT,
ADD COLUMN     "metadata" JSONB,
ADD COLUMN     "posX" DOUBLE PRECISION,
ADD COLUMN     "posY" DOUBLE PRECISION,
ADD COLUMN     "posZ" DOUBLE PRECISION,
ADD COLUMN     "rotX" DOUBLE PRECISION,
ADD COLUMN     "rotY" DOUBLE PRECISION,
ADD COLUMN     "rotZ" DOUBLE PRECISION,
ADD COLUMN     "scale" DOUBLE PRECISION DEFAULT 1.0,
ADD COLUMN     "spotlightIntensity" DOUBLE PRECISION DEFAULT 1.0,
ADD COLUMN     "wallId" TEXT;
